
block_1.end_pts = [points(170, :); points(155, :); points(160, :); points(164, :)];
block_1.functions = {[]; ...
                     points(155:160, :); ...
                     points(160:164, :); ...
                     points([164:168, 170], :)}; % points(164:170, :)

block_1.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_2.end_pts = [points(178, :); 75, -170; points(155, :); points(170, :)];
block_2.functions = {[]; ...
                     []; ...
                     []; ...
                     points(170:178, :)};

block_2.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_3.end_pts = [points(289, :); points(282, :); 75, -170; points(178, :)];
block_3.functions = {points(289:-1:282, :); ...
                     []; ...
                     []; ...
                     [points(178:3:181, :); points(294, :); [63.5, -195]; points(291:-1:289, :)]}; % :3:181

block_3.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_4.end_pts = [points(282, :); points(276, :); 88, -161; 75, -170];
block_4.functions = {[points(282:-1:282, :); points(279:-1:276, :)]; ...
                     []; ...
                     []; ...
                     []};

block_4.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_5.end_pts = [points(276, :); points(268, :); points(120, :); 88, -161];
block_5.functions = {[points(276, :); points(272:-1:268, :)]; ...
                     []; ...
                     []; ...
                     []};

block_5.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_6.end_pts = [points(257, :); points(110, :); points(120, :); points(268, :)]; % 
block_6.functions = {[]; ...
                     points(110:120, :); ...
                     []; ...
                     [points(268, :); points(266:-1:257, :), ]};

block_6.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_7.end_pts = [88, -161; points(120, :); points(124, :); points(141, :)];
block_7.functions = {[]; ...
                     points(120:1:124, :); ...
                     []; ...
                     []};

block_7.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_8.end_pts = [points(141, :); points(124, :); points(129, :); points(133, :)];
block_8.functions = {[]; ...
                     points(124:1:129, :); ...
                     points(129:1:133, :); ...
                     [points(133:2:138, :); points(141, :)]};

block_8.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_9.end_pts = [75, -170; 88, -161; points(141, :); points(155, :)];
block_9.functions = {[]; ...
                     []; ...
                     [points(141, :); points(149:2:155, :)]; ...
                     []};

block_9.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_10.end_pts = [points(369, :); 230, -135; points(93, :); points(374, :)]; % 225, -138
block_10.functions = {[]; ...
                      []; ...
                      [points(93, :); points(379:-1:374, :)]; ...
                      points(374:-1:369, :)};

block_10.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_11.end_pts = [points(363, :); points(357, :); 230, -135; points(369, :)];
block_11.functions = {points(363:-1:357, :); ... 
                      []; ...
                      []; ...
                      points(369:-1:363, :)}; 

block_11.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_12.end_pts = [points(357, :); points(341, :); points(332, :); 230, -135];
block_12.functions = {points(357:-1:341, :); ...
                      points(341:-1:332, :); ...
                      []; ...
                      []};

block_12.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_13.end_pts = [points(332, :); points(318, :); points(307, :); points(82, :)];
block_13.functions = {[points(332:-1:324, :); points(321:-1:318, :)]; ...
                      points(318:-1:307, :); ...
                      []; ...
                      []};

block_13.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_14.end_pts = [points(82, :); points(307, :); points(304, :); points(77, :)];
block_14.functions = {[]; ...
                      points(307:-1:304, :); ...
                      []; ...
                      flip(points(82:-1:77, :))};

block_14.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_15.end_pts = [points(77, :); points(304, :); points(300, :); points(73, :)];
block_15.functions = {[]; ...
                      points(304:-1:300, :); ...
                      []; ...
                      flip([points(77:-1:75, :); points(73, :)])};

block_15.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_16.end_pts = [points(73, :); points(300, :); points(56, :); points(68, :)];
block_16.functions = {[]; ...
                      [points(300, :); points(298, :); points(56, :)]; ...
                      flip([points(68:-1:59, :); points(56, :)]); ... 
                      flip(points(73:-1:68, :))};

block_16.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_17.end_pts = [230, -135; points(332, :); points(82, :); points(93, :)];
block_17.functions = {[]; ...
                      []; ...
                      flip([points(93:-1:84, :); points(82, :)]); ... 
                      []};

block_17.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_18.end_pts = [points(212, :); 26.5, -142; 26.5, 0; 0, 0];
block_18.end_pts = [points(212, :); 26.5, -142; 26.5, -13; 0, -13];
block_18.functions = {[]; ...
                      []; ...
                      []; ...
                      []};

block_18.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_19.end_pts = [points(206, :); 26.5, -167; 26.5, -142; points(212, :)];
block_19.functions = {[]; ...
                      []; ...
                      []; ...
                      []};

block_19.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_20.end_pts = [points(198, :); points(190, :); 26.5, -167; points(206, :)];
block_20.functions = {flip([points(190:196, :); points(198, :)]); ...
                      []; ...
                      []; ...
                      []};

block_20.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_21.end_pts = [points(190, :); points(178, :); points(170, :); 26.5, -167];
block_21.functions = {[points(190:-1:184, :); points(178, :)]; ...
                      flip(points(170:178, :)); ... 
                      []; ...
                      []};

block_21.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_22.end_pts = [points(257, :); points(93, :); points(82, :); points(110, :)];
block_22.functions = {[points(257, :); points(106:-1:93, :)]; ...
                      [points(93:-1:84, :); points(82, :)]; ... 
                      []; ...
                      []};

block_22.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_23.end_pts = [points(68, :); points(56, :); points(49, :); 136, 0];
block_23.end_pts = [points(68, :); points(56, :); points(49, :); 136, -13];
block_23.functions = {[points(68:-1:59, :); points(56, :)]; ... 
                      points(57:-1:49, :); ...
                      [points(49:-1:40, :); 136, -13]; ...
                      []};

block_23.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_24.end_pts = [points(129, :); points(68, :); 136, 0; 85.5, 0];
block_24.end_pts = [points(129, :); points(68, :); 136, -13; 85.5, -13];
block_24.functions = {[]; ...
                      []; ...
                      []; ...
                      []};

block_24.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_25.end_pts = [points(133, :); points(129, :); 85.5, 0; 74.5, 0];
block_25.end_pts = [points(133, :); points(129, :); 85.5, -13; 74.5, -13];
block_25.functions = {[points(133, :); 77.5, -129; points(129, :)]; ...
                      []; ...
                      []; ...
                      []};

block_25.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_26.end_pts = [points(160, :); points(133, :); 74.5, 0; 59.5, 0];
block_26.end_pts = [points(160, :); points(133, :); 74.5, -13; 59.5, -13];
block_26.functions = {[]; ...
                      []; ...
                      []; ...
                      []};

block_26.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_27.end_pts = [points(164, :); points(160, :); 59.5, 0; 48, 0];
block_27.end_pts = [points(164, :); points(160, :); 59.5, -13; 48, -13];
block_27.functions = {flip(points(160:164, :)); ...
                      []; ...
                      []; ...
                      []};

block_27.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% block_28.end_pts = [26.5, -142; points(164, :); 48, 0; 26.5, 0];
block_28.end_pts = [26.5, -142; points(164, :); 48, -13; 26.5, -13];
block_28.functions = {[]; ...
                      []; ...
                      []; ...
                      []};

block_28.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_29.end_pts = [26.5, -167; points(170, :); points(164, :); 26.5, -142];
block_29.functions = {[]; ...
                      flip(points([164:168, 170], :)); ... 
                      []; ...
                      []};

block_29.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_30.end_pts = [points(155, :); points(141, :); points(133, :); points(160, :)];
block_30.functions = {flip([points(141, :); points(149:2:155, :)]); ...
                      [points(141, :); flip(points(133:2:138, :))]; ...
                      []; ...
                      points(160:-1:155, :)};

block_30.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_31.end_pts = [points(124, :); points(73, :); points(68, :); points(129, :)];
block_31.functions = {[]; ...
                      points(73:-1:68, :); ...
                      []; ...
                      flip(points(124:1:129, :))};

block_31.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_32.end_pts = [points(120, :); points(77, :); points(73, :); points(124, :)];
block_32.functions = {[]; ...
                      [points(77:-1:75, :); points(73, :)]; ...
                      []; ...
                      flip(points(120:1:124, :))};

block_32.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

block_33.end_pts = [points(110, :); points(82, :); points(77, :); points(120, :)];
block_33.functions = {[]; ...
                      points(82:-1:77, :); ...
                      []; ...
                      flip(points(110:120, :))};

block_33.derivatives = {};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

points_water = {block_1.end_pts, block_2.end_pts, ...
                block_3.end_pts, block_4.end_pts, ...
                block_5.end_pts, block_6.end_pts, ...
                block_7.end_pts, block_8.end_pts, ...
                block_9.end_pts, block_10.end_pts, ...
                block_11.end_pts, block_12.end_pts, ...
                block_13.end_pts, block_14.end_pts, ...
                block_15.end_pts, block_16.end_pts, ...
                block_17.end_pts, block_18.end_pts, ...
                block_19.end_pts, block_20.end_pts, ...
                block_21.end_pts, block_22.end_pts, ...
                block_23.end_pts, block_24.end_pts, ...
                block_25.end_pts, block_26.end_pts, ...
                block_27.end_pts, block_28.end_pts, ...
                block_29.end_pts, block_30.end_pts, ...
                block_31.end_pts, block_32.end_pts, ...
                block_33.end_pts};
functions_water = {block_1.functions, block_2.functions, ...
                   block_3.functions, block_4.functions, ...
                   block_5.functions, block_6.functions, ...
                   block_7.functions, block_8.functions, ...
                   block_9.functions, block_10.functions, ...
                   block_11.functions, block_12.functions, ...
                   block_13.functions, block_14.functions, ...
                   block_15.functions, block_16.functions, ...
                   block_17.functions, block_18.functions, ...
                   block_19.functions, block_20.functions, ...
                   block_21.functions, block_22.functions, ...
                   block_23.functions, block_24.functions, ...
                   block_25.functions, block_26.functions, ...
                   block_27.functions, block_28.functions, ...
                   block_29.functions, block_30.functions, ...
                   block_31.functions, block_32.functions, ...
                   block_33.functions};
derivatives_water = {block_1.derivatives, block_2.derivatives, ...
                     block_3.derivatives, block_4.derivatives, ...
                     block_5.derivatives, block_6.derivatives, ...
                     block_7.derivatives, block_8.derivatives, ...
                     block_9.derivatives, block_10.derivatives, ...
                     block_11.derivatives, block_12.derivatives, ...
                     block_13.derivatives, block_14.derivatives, ...
                     block_15.derivatives, block_16.derivatives, ...
                     block_17.derivatives, block_18.derivatives, ...
                     block_19.derivatives, block_20.derivatives, ...
                     block_21.derivatives, block_22.derivatives, ...
                     block_23.derivatives, block_24.derivatives, ...
                     block_25.derivatives, block_26.derivatives, ...
                     block_27.derivatives, block_28.derivatives, ...
                     block_29.derivatives, block_30.derivatives, ...
                     block_31.derivatives, block_32.derivatives, ...
                     block_33.derivatives};

water_block_N = 33;
ice_block_N = 17;
def = FoursidedAmundsen(points_water, functions_water, derivatives_water, water_block_N);
def_ice = FoursidedIceAmundsen(points_water(1:ice_block_N), functions_water(1:ice_block_N), derivatives_water(1:ice_block_N), ice_block_N);

g = def.getGrid(m);

g_ice = def_ice.getGrid(m);
figure()
def.show([], true, m)
% figure()
% def_ice.show([], true, m);

n_water = g.nPoints;
n_ice   = g_ice.nPoints;